
input_filenames:
  - zotero_sample.docx

output_filename: bibliography.html

cache_duration_in_minutes: 5 # set to 0 if caching of zotero tags is not desired

title: Bibliography

style: chicago-fullnote-bibliography

sections:

  - primary sources:
    - tag1
    - tag2

  - secondary sources:
    - tag3
